//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Expr.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class ExprParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, NUM=3, WS=4, OP_ADD=5, OP_SUB=6, OP_MUL=7, OP_DIV=8, OP_POW=9, 
		OP_EQ=10, OP_LS=11, OP_GR=12, OP_NE=13, OP_LE=14, OP_GE=15, SEP_COM=16, 
		ID=17;
	public const int
		RULE_compileUnit = 0, RULE_expr = 1, RULE_funcArgs = 2;
	public static readonly string[] ruleNames = {
		"compileUnit", "expr", "funcArgs"
	};

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", null, null, "'+'", "'-'", "'*'", "'/'", "'^'", "'='", 
		"'<'", "'>'", "'!='", "'<='", "'>='", "','"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, "NUM", "WS", "OP_ADD", "OP_SUB", "OP_MUL", "OP_DIV", 
		"OP_POW", "OP_EQ", "OP_LS", "OP_GR", "OP_NE", "OP_LE", "OP_GE", "SEP_COM", 
		"ID"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Expr.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ExprParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public ExprParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public ExprParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class CompileUnitContext : ParserRuleContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode Eof() { return GetToken(ExprParser.Eof, 0); }
		public CompileUnitContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_compileUnit; } }
		public override void EnterRule(IParseTreeListener listener) {
			IExprListener typedListener = listener as IExprListener;
			if (typedListener != null) typedListener.EnterCompileUnit(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IExprListener typedListener = listener as IExprListener;
			if (typedListener != null) typedListener.ExitCompileUnit(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IExprVisitor<TResult> typedVisitor = visitor as IExprVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCompileUnit(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CompileUnitContext compileUnit() {
		CompileUnitContext _localctx = new CompileUnitContext(Context, State);
		EnterRule(_localctx, 0, RULE_compileUnit);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 6; expr(0);
			State = 7; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class P0ExprContext : ExprContext {
		public ExprContext left;
		public IToken op;
		public ExprContext right;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode OP_POW() { return GetToken(ExprParser.OP_POW, 0); }
		public ITerminalNode OP_MUL() { return GetToken(ExprParser.OP_MUL, 0); }
		public ITerminalNode OP_DIV() { return GetToken(ExprParser.OP_DIV, 0); }
		public ITerminalNode OP_ADD() { return GetToken(ExprParser.OP_ADD, 0); }
		public ITerminalNode OP_SUB() { return GetToken(ExprParser.OP_SUB, 0); }
		public ITerminalNode OP_EQ() { return GetToken(ExprParser.OP_EQ, 0); }
		public ITerminalNode OP_NE() { return GetToken(ExprParser.OP_NE, 0); }
		public ITerminalNode OP_GR() { return GetToken(ExprParser.OP_GR, 0); }
		public ITerminalNode OP_LS() { return GetToken(ExprParser.OP_LS, 0); }
		public ITerminalNode OP_LE() { return GetToken(ExprParser.OP_LE, 0); }
		public ITerminalNode OP_GE() { return GetToken(ExprParser.OP_GE, 0); }
		public P0ExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IExprListener typedListener = listener as IExprListener;
			if (typedListener != null) typedListener.EnterP0Expr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IExprListener typedListener = listener as IExprListener;
			if (typedListener != null) typedListener.ExitP0Expr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IExprVisitor<TResult> typedVisitor = visitor as IExprVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitP0Expr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PurenExprContext : ExprContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public PurenExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IExprListener typedListener = listener as IExprListener;
			if (typedListener != null) typedListener.EnterPurenExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IExprListener typedListener = listener as IExprListener;
			if (typedListener != null) typedListener.ExitPurenExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IExprVisitor<TResult> typedVisitor = visitor as IExprVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPurenExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FuncExprContext : ExprContext {
		public IToken func;
		public FuncArgsContext args;
		public ITerminalNode ID() { return GetToken(ExprParser.ID, 0); }
		public FuncArgsContext funcArgs() {
			return GetRuleContext<FuncArgsContext>(0);
		}
		public FuncExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IExprListener typedListener = listener as IExprListener;
			if (typedListener != null) typedListener.EnterFuncExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IExprListener typedListener = listener as IExprListener;
			if (typedListener != null) typedListener.ExitFuncExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IExprVisitor<TResult> typedVisitor = visitor as IExprVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFuncExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NegExprContext : ExprContext {
		public ITerminalNode OP_SUB() { return GetToken(ExprParser.OP_SUB, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public NegExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IExprListener typedListener = listener as IExprListener;
			if (typedListener != null) typedListener.EnterNegExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IExprListener typedListener = listener as IExprListener;
			if (typedListener != null) typedListener.ExitNegExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IExprVisitor<TResult> typedVisitor = visitor as IExprVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNegExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumExprContext : ExprContext {
		public IToken value;
		public ITerminalNode NUM() { return GetToken(ExprParser.NUM, 0); }
		public NumExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IExprListener typedListener = listener as IExprListener;
			if (typedListener != null) typedListener.EnterNumExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IExprListener typedListener = listener as IExprListener;
			if (typedListener != null) typedListener.ExitNumExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IExprVisitor<TResult> typedVisitor = visitor as IExprVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 2;
		EnterRecursionRule(_localctx, 2, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 22;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__0:
				{
				_localctx = new PurenExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 10; Match(T__0);
				State = 11; expr(0);
				State = 12; Match(T__1);
				}
				break;
			case OP_SUB:
				{
				_localctx = new NegExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 14; Match(OP_SUB);
				State = 15; expr(7);
				}
				break;
			case NUM:
				{
				_localctx = new NumExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 16; ((NumExprContext)_localctx).value = Match(NUM);
				}
				break;
			case ID:
				{
				_localctx = new FuncExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 17; ((FuncExprContext)_localctx).func = Match(ID);
				State = 18; Match(T__0);
				State = 19; ((FuncExprContext)_localctx).args = funcArgs();
				State = 20; Match(T__1);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 38;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 36;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
					case 1:
						{
						_localctx = new P0ExprContext(new ExprContext(_parentctx, _parentState));
						((P0ExprContext)_localctx).left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 24;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 25; ((P0ExprContext)_localctx).op = Match(OP_POW);
						State = 26; ((P0ExprContext)_localctx).right = expr(4);
						}
						break;
					case 2:
						{
						_localctx = new P0ExprContext(new ExprContext(_parentctx, _parentState));
						((P0ExprContext)_localctx).left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 27;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 28;
						((P0ExprContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==OP_MUL || _la==OP_DIV) ) {
							((P0ExprContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 29; ((P0ExprContext)_localctx).right = expr(4);
						}
						break;
					case 3:
						{
						_localctx = new P0ExprContext(new ExprContext(_parentctx, _parentState));
						((P0ExprContext)_localctx).left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 30;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 31;
						((P0ExprContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==OP_ADD || _la==OP_SUB) ) {
							((P0ExprContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 32; ((P0ExprContext)_localctx).right = expr(3);
						}
						break;
					case 4:
						{
						_localctx = new P0ExprContext(new ExprContext(_parentctx, _parentState));
						((P0ExprContext)_localctx).left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 33;
						if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
						State = 34;
						((P0ExprContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << OP_EQ) | (1L << OP_LS) | (1L << OP_GR) | (1L << OP_NE) | (1L << OP_LE) | (1L << OP_GE))) != 0)) ) {
							((P0ExprContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 35; ((P0ExprContext)_localctx).right = expr(2);
						}
						break;
					}
					} 
				}
				State = 40;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class FuncArgsContext : ParserRuleContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode[] SEP_COM() { return GetTokens(ExprParser.SEP_COM); }
		public ITerminalNode SEP_COM(int i) {
			return GetToken(ExprParser.SEP_COM, i);
		}
		public FuncArgsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_funcArgs; } }
		public override void EnterRule(IParseTreeListener listener) {
			IExprListener typedListener = listener as IExprListener;
			if (typedListener != null) typedListener.EnterFuncArgs(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IExprListener typedListener = listener as IExprListener;
			if (typedListener != null) typedListener.ExitFuncArgs(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IExprVisitor<TResult> typedVisitor = visitor as IExprVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFuncArgs(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FuncArgsContext funcArgs() {
		FuncArgsContext _localctx = new FuncArgsContext(Context, State);
		EnterRule(_localctx, 4, RULE_funcArgs);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 41; expr(0);
			State = 46;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==SEP_COM) {
				{
				{
				State = 42; Match(SEP_COM);
				State = 43; expr(0);
				}
				}
				State = 48;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 1: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 4);
		case 1: return Precpred(Context, 3);
		case 2: return Precpred(Context, 2);
		case 3: return Precpred(Context, 1);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x13', '\x34', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x5', '\x3', '\x19', 
		'\n', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\a', '\x3', '\'', '\n', '\x3', '\f', 
		'\x3', '\xE', '\x3', '*', '\v', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\a', '\x4', '/', '\n', '\x4', '\f', '\x4', '\xE', '\x4', '\x32', 
		'\v', '\x4', '\x3', '\x4', '\x2', '\x3', '\x4', '\x5', '\x2', '\x4', '\x6', 
		'\x2', '\x5', '\x3', '\x2', '\t', '\n', '\x3', '\x2', '\a', '\b', '\x3', 
		'\x2', '\f', '\x11', '\x2', '\x38', '\x2', '\b', '\x3', '\x2', '\x2', 
		'\x2', '\x4', '\x18', '\x3', '\x2', '\x2', '\x2', '\x6', '+', '\x3', '\x2', 
		'\x2', '\x2', '\b', '\t', '\x5', '\x4', '\x3', '\x2', '\t', '\n', '\a', 
		'\x2', '\x2', '\x3', '\n', '\x3', '\x3', '\x2', '\x2', '\x2', '\v', '\f', 
		'\b', '\x3', '\x1', '\x2', '\f', '\r', '\a', '\x3', '\x2', '\x2', '\r', 
		'\xE', '\x5', '\x4', '\x3', '\x2', '\xE', '\xF', '\a', '\x4', '\x2', '\x2', 
		'\xF', '\x19', '\x3', '\x2', '\x2', '\x2', '\x10', '\x11', '\a', '\b', 
		'\x2', '\x2', '\x11', '\x19', '\x5', '\x4', '\x3', '\t', '\x12', '\x19', 
		'\a', '\x5', '\x2', '\x2', '\x13', '\x14', '\a', '\x13', '\x2', '\x2', 
		'\x14', '\x15', '\a', '\x3', '\x2', '\x2', '\x15', '\x16', '\x5', '\x6', 
		'\x4', '\x2', '\x16', '\x17', '\a', '\x4', '\x2', '\x2', '\x17', '\x19', 
		'\x3', '\x2', '\x2', '\x2', '\x18', '\v', '\x3', '\x2', '\x2', '\x2', 
		'\x18', '\x10', '\x3', '\x2', '\x2', '\x2', '\x18', '\x12', '\x3', '\x2', 
		'\x2', '\x2', '\x18', '\x13', '\x3', '\x2', '\x2', '\x2', '\x19', '(', 
		'\x3', '\x2', '\x2', '\x2', '\x1A', '\x1B', '\f', '\x6', '\x2', '\x2', 
		'\x1B', '\x1C', '\a', '\v', '\x2', '\x2', '\x1C', '\'', '\x5', '\x4', 
		'\x3', '\x6', '\x1D', '\x1E', '\f', '\x5', '\x2', '\x2', '\x1E', '\x1F', 
		'\t', '\x2', '\x2', '\x2', '\x1F', '\'', '\x5', '\x4', '\x3', '\x6', ' ', 
		'!', '\f', '\x4', '\x2', '\x2', '!', '\"', '\t', '\x3', '\x2', '\x2', 
		'\"', '\'', '\x5', '\x4', '\x3', '\x5', '#', '$', '\f', '\x3', '\x2', 
		'\x2', '$', '%', '\t', '\x4', '\x2', '\x2', '%', '\'', '\x5', '\x4', '\x3', 
		'\x4', '&', '\x1A', '\x3', '\x2', '\x2', '\x2', '&', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '&', ' ', '\x3', '\x2', '\x2', '\x2', '&', '#', '\x3', '\x2', 
		'\x2', '\x2', '\'', '*', '\x3', '\x2', '\x2', '\x2', '(', '&', '\x3', 
		'\x2', '\x2', '\x2', '(', ')', '\x3', '\x2', '\x2', '\x2', ')', '\x5', 
		'\x3', '\x2', '\x2', '\x2', '*', '(', '\x3', '\x2', '\x2', '\x2', '+', 
		'\x30', '\x5', '\x4', '\x3', '\x2', ',', '-', '\a', '\x12', '\x2', '\x2', 
		'-', '/', '\x5', '\x4', '\x3', '\x2', '.', ',', '\x3', '\x2', '\x2', '\x2', 
		'/', '\x32', '\x3', '\x2', '\x2', '\x2', '\x30', '.', '\x3', '\x2', '\x2', 
		'\x2', '\x30', '\x31', '\x3', '\x2', '\x2', '\x2', '\x31', '\a', '\x3', 
		'\x2', '\x2', '\x2', '\x32', '\x30', '\x3', '\x2', '\x2', '\x2', '\x6', 
		'\x18', '&', '(', '\x30',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
